pipeline {
    agent { 
      docker {
        image 'maven:3.9.8-sapmachine-21'
        args '-v $HOME/.m2:/root/.m2'
      }
    }
   
    stages{
    
      stage("build"){
        when {
          changeset "**/worker/**"
        }

        steps{
          echo 'Compiling worker app'
          dir('worker'){
            sh 'mvn compile'
          }
        }
      }
      stage("test"){
        when {
          changeset "**/worker/**"
        }

        steps{
          echo 'Running Unit Tests on worker app'
          dir('worker'){
            sh 'mvn clean test'
          }
        }
      }
      stage("package"){
        when {
          branch "master"
          changeset "**/worker/**"
        }

       steps{
          echo 'Packaging worker app'
          dir('worker'){
            sh 'mvn package -DskipTests'
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
          }
        }
      }
      stage("docker-package") {
        agent any
        steps {
          echo 'Packaging worker app with docker'
          script {
            docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
              def workerImage = docker.build("sicness9/worker:v${env.BUILD_ID}", "./worker")
              workerImage.push()
              workerImage.push("latest")
          }
          }
        }
      }
    }

    post{
      always{
        echo 'multibranch pipeline job for worker is completed..'
      }
    }
}
